baseURL = 'https://switchboardtechservices.com/'
languageCode = 'en-us'
title = 'Switchboard Tech Services - Kirksville, Missouri'
theme = 'terminal'

# Basic site params
enableRobotsTXT = true
canonifyURLs = true

[params]
  readMore = "Read more →"
  defaultDescription = "Switchboard Tech Services — Local Tech Help, Linux conversions, and repair services in Kirksville, Missouri."
  defaultImage = "/images/theswitchboard.jpg"
  
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  toc = true

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"
  

  # Business identity
  author = "Leo Blanchette"
  subtitle = "Local Tech Help, Tech Maintenance and Repair, Linux Conversions"
  description = "Switchboard Tech Services provides reliable computer and tech support in Kirksville, Missouri. Call or text today for local service."

[languages]
  [languages.en]
    languageName = "English"
    title = "Switchboard Tech Services | Kirksville Computer Repair & IT Help"
    copyright = "© 2025 Switchboard Tech Services, LLC — Kirksville, Missouri · Licensed · Locally Operated"
    readMore = "Read more →"
    readOtherPosts = "More field notes"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"

    [languages.en.params.logo]
      logoText = "Switchboard Tech Services, Kirksville"
      logoHomeLink = "/"

[menu]
  # Core navigation — only what you want in the header
  [[menu.main]]
    identifier = "services"
    name = "Services / Prices"
    url = "/services/"
    weight = 1
  # Optional — third anchor if you want more than bare-minimum
 [[menu.main]]
    identifier = "who"
    name = "Who I Help"
    url = "/who/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.main]]
    identifier = "guides"
    name = "Guides"
    url = "/guides/"
    weight = 5

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6


# Deployment output
[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  page = ["HTML", "JSON"]

# Sitemap & SEO
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params.business]
  name   = "Switchboard Tech Services, LLC"
  street = "PO Box 594"
  city   = "Kirksville"
  state  = "MO"
  zip    = "63501"
  phone  = "+1.660.956.1108"
  email  = "theswitchboard@protonmail.com"
  url    = "https://switchboardtechservices.com"
  sameAs = [
    "https://www.facebook.com/SwitchboardTechServices/",
    "https://www.yelp.com/biz/switchboard-tech-services-kirksville"
  ]

# Modern way
[services]
  [services.googleAnalytics]
    ID = "G-SZ853YL51X"

# Optional privacy hardening
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[taxonomies]
  category = "categories"
  tag = "tags"