name: Hugo Build and Deploy to Opalstack

on:
  push:
    branches:
      - main   # adjust if you deploy from a different branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # This pulls the unencrypted Private Key from your GitHub secret
          ssh-private-key: ${{ secrets.THESWITCHBOARD_OPALSTACK }} 

      # 2. Add known_hosts (Ensures the server host is trusted)
      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan opal18.opalstack.com >> ~/.ssh/known_hosts

      # 3. Deploy to Opalstack with rsync
      - name: Deploy to Opalstack with rsync
        run: |
          # rsync now uses the key made available by the SSH agent
          rsync -avz --delete \
            public/ theswitchboard@opal18.opalstack.com:/home/theswitchboard/apps/switchboardtechservices/