name: Hugo Build and Deploy to Opalstack

on:
  push:
    branches:
      - main   # adjust if you deploy from a different branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan opal18.opalstack.com >> ~/.ssh/known_hosts

      - name: Deploy to Opalstack with rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa" \
            public/ theswitchboard@<opal18.opalstack.com:apps/switchboardtechservices.com/
